"""add_trust_reputation_fields_and_history_table

Revision ID: 0efdcec73b2a
Revises: 46ef64e38314
Create Date: 2025-12-14 17:51:42.430520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0efdcec73b2a'
down_revision: Union[str, Sequence[str], None] = '46ef64e38314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trust_history',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=50), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('old_score', sa.Integer(), nullable=False),
    sa.Column('new_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trust_history_user_created', 'trust_history', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_trust_history_user_id'), 'trust_history', ['user_id'], unique=False)
    op.add_column('users', sa.Column('successful_submissions', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('total_submissions', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('pending_role_upgrade', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('is_locked', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    op.add_column('users', sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('report_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'report_count')
    op.drop_column('users', 'locked_at')
    op.drop_column('users', 'is_locked')
    op.drop_column('users', 'pending_role_upgrade')
    op.drop_column('users', 'total_submissions')
    op.drop_column('users', 'successful_submissions')
    op.drop_index(op.f('ix_trust_history_user_id'), table_name='trust_history')
    op.drop_index('ix_trust_history_user_created', table_name='trust_history')
    op.drop_table('trust_history')
    # ### end Alembic commands ###
