"""add roles trust score reputation to users

Revision ID: 17785f924a97
Revises: 93c7bad2b888
Create Date: 2025-12-14 15:09:22.053158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17785f924a97'
down_revision: Union[str, Sequence[str], None] = '93c7bad2b888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'["user"]\'::jsonb'), nullable=False))
    op.add_column('users', sa.Column('trust_score', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('reputation_percentage', sa.Float(), server_default=sa.text('100.0'), nullable=False))
    op.create_index('ix_users_trust_score', 'users', ['trust_score'], unique=False)
    
    # Add check constraints
    op.create_check_constraint('ck_users_roles_array', 'users', "jsonb_typeof(roles) = 'array'")
    op.create_check_constraint('ck_users_trust_score_positive', 'users', 'trust_score >= 0')
    op.create_check_constraint('ck_users_reputation_range', 'users', 'reputation_percentage >= 0 AND reputation_percentage <= 100')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop check constraints
    op.drop_constraint('ck_users_reputation_range', 'users', type_='check')
    op.drop_constraint('ck_users_trust_score_positive', 'users', type_='check')
    op.drop_constraint('ck_users_roles_array', 'users', type_='check')
    
    op.drop_index('ix_users_trust_score', table_name='users')
    op.drop_column('users', 'reputation_percentage')
    op.drop_column('users', 'trust_score')
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###
