"""initial schema

Revision ID: 30d47b0b071b
Revises: 
Create Date: 2025-12-14 13:32:55.282743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30d47b0b071b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('is_blacklisted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('avatar_key', sa.String(length=512), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'["user"]\'::jsonb'), nullable=False),
    sa.Column('trust_score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reputation_percentage', sa.Float(), server_default=sa.text('100.0'), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('successful_submissions', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_submissions', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('pending_role_upgrade', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_locked', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(roles) = 'array'", name='ck_users_roles_array'),
    sa.CheckConstraint("jsonb_typeof(scopes) = 'array'", name='ck_users_scopes_array'),
    sa.CheckConstraint('reputation_percentage >= 0 AND reputation_percentage <= 100', name='ck_users_reputation_range'),
    sa.CheckConstraint('trust_score >= 0', name='ck_users_trust_score_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.create_index('ix_users_name_lower', 'users', [sa.literal_column('lower(name)')], unique=True)
    op.create_index('ix_users_trust_score', 'users', ['trust_score'], unique=False)
    op.create_table('content_reports',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=False),
    sa.Column('target', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_content_reports_created', 'content_reports', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_content_reports_reporter', 'content_reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_content_reports_reporter_id'), 'content_reports', ['reporter_id'], unique=False)
    op.create_index('ix_content_reports_status', 'content_reports', ['status'], unique=False)
    op.create_index('ix_content_reports_target_actor', 'content_reports', [sa.literal_column("(target->>'actor_id')")], unique=False)
    op.create_index('ux_content_reports_unique_edit', 'content_reports', ['reporter_id', sa.literal_column("(target->>'edit_id')")], unique=True, postgresql_where=sa.text("status IN ('pending', 'approved')"))
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_ip', sa.String(length=45), nullable=True),
    sa.CheckConstraint('expires_at > issued_at', name='ck_refresh_tokens_expiry'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_index('ix_refresh_tokens_active', 'refresh_tokens', ['expires_at'], unique=False, postgresql_where=sa.text('revoked = FALSE'))
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('ux_refresh_tokens_family_current', 'refresh_tokens', ['family_id'], unique=True, postgresql_where=sa.text('is_current = TRUE'))
    op.create_table('trust_history',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=50), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('old_score', sa.Integer(), nullable=False),
    sa.Column('new_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trust_history_user_created', 'trust_history', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_trust_history_user_id'), 'trust_history', ['user_id'], unique=False)
    op.create_table('verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=64), server_default=sa.text("'email_verification'"), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_verification_tokens_expires_at', 'verification_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_verification_tokens_id'), 'verification_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_verification_tokens_user_id'), 'verification_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_tokens_user_id'), table_name='verification_tokens')
    op.drop_index(op.f('ix_verification_tokens_id'), table_name='verification_tokens')
    op.drop_index('ix_verification_tokens_expires_at', table_name='verification_tokens')
    op.drop_table('verification_tokens')
    op.drop_index(op.f('ix_trust_history_user_id'), table_name='trust_history')
    op.drop_index('ix_trust_history_user_created', table_name='trust_history')
    op.drop_table('trust_history')
    op.drop_index('ux_refresh_tokens_family_current', table_name='refresh_tokens', postgresql_where=sa.text('is_current = TRUE'))
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_active', table_name='refresh_tokens', postgresql_where=sa.text('revoked = FALSE'))
    op.drop_table('refresh_tokens')
    op.drop_index('ux_content_reports_unique_edit', table_name='content_reports', postgresql_where=sa.text("status IN ('pending', 'approved')"))
    op.drop_index('ix_content_reports_target_actor', table_name='content_reports')
    op.drop_index('ix_content_reports_status', table_name='content_reports')
    op.drop_index(op.f('ix_content_reports_reporter_id'), table_name='content_reports')
    op.drop_index('ix_content_reports_reporter', table_name='content_reports')
    op.drop_index('ix_content_reports_created', table_name='content_reports')
    op.drop_table('content_reports')
    op.drop_index('ix_users_trust_score', table_name='users')
    op.drop_index('ix_users_name_lower', table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index('ix_users_email_lower', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
