"""Update user table

Revision ID: 4af57f0759ed
Revises: 2fd4c5c0f3cf
Create Date: 2025-12-12 17:34:37.440998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af57f0759ed'
down_revision: Union[str, Sequence[str], None] = '2fd4c5c0f3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_verification_tokens_id'), 'verification_tokens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_tokens_id'), table_name='verification_tokens')
    op.drop_column('users', 'expires_at')
    # ### end Alembic commands ###
